version: "3.9"
volumes:
  postgresql-data:
  pgadmin-data:

services:
  postgresql:
    container_name: blog-postgresql
    image: postgres:14
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "camus"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_PASSWORD: 199326
      POSTGRES_USER: camus
      POSTGRES_DB: blog_db
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/data

  pgadmin-compose:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "16543:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgresql
